version: '3.3'
services:
  chat-poller:
    build:
      context: ./projects/chat-poller
      dockerfile: Dockerfile
    restart: always
    env_file: ./projects/chat-poller/.env

  web-app:
    build:
      context: ./projects/web-app
      dockerfile: Dockerfile
    restart: 'no'
    env_file: ./projects/web-app/.env
    volumes:
      - ./projects/web-app/src/views:/dist/views
      - ./projects/web-app/assets:/dist/assets
    ports:
      - 3000:3000
